-- from the terminal run:
-- psql < seed.sql

DROP DATABASE IF EXISTS combinations;

CREATE DATABASE combinations;

\c combinations

CREATE TABLE DEALS
(
  ID SERIAL,
  YEAR TEXT NOT NULL,
  MONTH TEXT NOT NULL,
  DAY TEXT NOT NULL,
  BOARD TEXT NOT NULL,
  HANDS TEXT [],
  PRIMARY KEY (YEAR,MONTH,DAY,BOARD)
);

CREATE TABLE DISTRIBUTIONS
(
  SUIT TEXT NOT NULL,
  LONG TEXT NOT NULL,
  SHORT TEXT NOT NULL,
  FREQUENCY INTEGER,
  PRIMARY KEY (SUIT,LONG,SHORT)
);
