-- from the terminal run:
-- psql < seed.sql

DROP DATABASE IF EXISTS combinations;

CREATE DATABASE combinations;

\c combinations

CREATE TABLE DEALS
(
  ID SERIAL,
  YEAR TEXT NOT NULL,
  MONTH TEXT NOT NULL,
  DAY TEXT NOT NULL,
  BOARD INTEGER NOT NULL,
  HANDS TEXT NOT NULL,
  RESULTS TEXT NOT NULL,
  PRIMARY KEY (YEAR,MONTH,DAY,BOARD)
);

CREATE TABLE DISTRIBUTIONS
(
  ID SERIAL,
  YEAR TEXT NOT NULL,
  MONTH TEXT NOT NULL,
  DAY TEXT NOT NULL,
  BOARD INTEGER NOT NULL,
  SUIT TEXT NOT NULL,
  LONG TEXT NOT NULL,
  SHORT TEXT NOT NULL,
  RESULTS TEXT NOT NULL,
  PRIMARY KEY (YEAR, MONTH, DAY, BOARD, SUIT, LONG, SHORT)
);
