-- from the terminal run:
-- psql < seed.sql

DROP DATABASE IF EXISTS combinations;

CREATE DATABASE combinations;

\c combinations

CREATE TABLE DEALS
(
  ID SERIAL,
  YEAR TEXT NOT NULL,
  MONTH TEXT NOT NULL,
  DAY TEXT NOT NULL,
  BOARD INTEGER NOT NULL,
  HANDS TEXT NOT NULL,
  RESULTS TEXT NOT NULL,
  PRIMARY KEY (YEAR,MONTH,DAY,BOARD)
);

CREATE TABLE DISTRIBUTIONS
(
  ID SERIAL,
  YEAR TEXT NOT NULL,
  MONTH TEXT NOT NULL,
  DAY TEXT NOT NULL,
  BOARD INTEGER NOT NULL,
  SUIT TEXT NOT NULL,
  LONG TEXT NOT NULL,
  SHORT TEXT NOT NULL,
  RESULTS INTEGER[],
  N_1 INTEGER,
  S_1 INTEGER,
  H_1 INTEGER,
  D_1 INTEGER,
  C_1 INTEGER,
  N_2 INTEGER,
  S_2 INTEGER,
  H_2 INTEGER,
  D_2 INTEGER,
  C_2 INTEGER,
  PRIMARY KEY (YEAR, MONTH, DAY, BOARD, SUIT, LONG, SHORT)
);
